apiVersion: v1
kind: Config
clusters:
- name: local-k8s
  cluster:
    server: https://localhost.localstack.cloud:4510
    insecure-skip-tls-verify: true
contexts:
- name: local-k8s
  context:
    cluster: local-k8s
    user: local-user
current-context: local-k8s
users:
- name: local-user
  user:
    username: admin
    password: admin
