apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-az-deployment
  labels:
    app: multi-az-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: multi-az-app
  template:
    metadata:
      labels:
        app: multi-az-app
    spec:
      # Set topology for distributing pods across different zones
      topologySpreadConstraints:
      - maxSkew: 1 # Difference between zones no more than 1 pod
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: multi-az-app
      # Select nodes based on the role label
      nodeSelector:
        role: app

      # Mandatory rule: select nodes only with the specified label
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - app

        # Try to distribute pods on different nodes for better fault tolerance
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - multi-az-app
              topologyKey: "kubernetes.io/hostname"

      containers:
      - name: application
        image: nginx:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
